### ISSUE TITLE
Initial support for bridge multicast-snooping

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#303]
Extend native bridge yang model with basic support for filtering and adding static MDB entries, both IP and MAC multicast entries.

> **Note:** due to how the MDB is implemented in the Linux bridge it is not possible to add MDB entries when multicast snooping is off.  This needs to be documented clearly.

- Some of the global bridge options, including per VLAN (VLAN global options):
  - [x] on/off multicast snooping (filtering)
  - [x] on/off querier
  - [x] on/off proxy querier, or allow using interface address
  - [x] querier interval (default 125s)
- Per-port options
  - [x] static multicast-router
  - [x] fast-leave
  - [x] multicast flood
- MDB
  - [ ] Add static mdb entry (MAC and IP)
  - [ ] Del static mdb entry (MAC and IP)
- Operational
  - [ ] List mdb
  - [ ] List multicast router ports
  - [ ] List multicast routers, per bridge or per VLAN
  - [ ] List multicast status: on/off settings
  - [ ] List per-port settings: flood, fast-leave, etc.
- Kernel
  - [X] Forward port `mcast_flood_always` support for bridge
  - [ ] Finalize kernel patch(es) and upstream
- Documentation
  - [ ] Update `doc/networking.md`
  - [ ] Mention filtering limitation (snooping must be on)
  - [ ] Describe `mcast_flood` and how it is good for MAC multicast, e.g. industrial fieldbus protocols

### Tasks
 - Verify adding ports to a bridge enables snooping on ports
 - Verify toggling per-port multicast options take at runtime
 - ...

**Comment by mattiaswal** [comment]
Propose to add two more tests:
igmp_vlan
purpose: To verify that the VLAN integrity is respected.
<pre>
#
#
#            VLAN1              VLAN3                          VLAN1               VLAN3
#           10.0.1.1           10.0.2.1                       10.0.1.2            10.0.2.2
#             \                    /                           \                     /
#              \                  /                             \                   /
#               \                /                               \                 /
#                \--------------/        VLAN 1,2  T              \---------------/
#                |    DUT1      +---------------------------------+      DUT2     |
#                |              |                                 |               |
#                +--------------+                                 +-----+---------+
#         VLAN1 U|       VLAN2 U|                               VLAN1 U |        | VLAN2 T
#                |              |                                       |        |
#                |              |                                       |        |
#                |              |                                       |        |
#                |              |                                       |        |
#     +-------+  |             +----------+                 +------------+       +-------+
#     | msend +--+             | mreceive |                 | mreceive   |       | msend |
#     +-------+                +----------+                 +------------+       +-------+
#      10.0.1.11                 10.0.2.11                      10.0.1.22              10.0.2.22
#

</pre>

igmp_tagged
purpose: To verify that IGMP/MLD frames get tagged on tagged ports.
<pre>
#                      VLAN1                                          VLAN1
#                     10.0.1.1                                       10.0.1.2
#                        |                                               |
#                        |                                               |
#                        |                                               |
#                +-------+------+        VLAN1 T                  +------+--------+
#                |    DUT1      +---------------------------------+      DUT2     |
#                |              |                                 |               |
#                +--------------+                                 +-----+---------+
#         VLAN1 U|              |                               VLAN1 U |
#                |              | VLAN1 T                               |
#                |              |                                       |
#    VLAN1       |              |                                       |
#    10.0.1.2    |              +-------------+                         |
#     +-------+  |              |    PC       |                  +------+-----+
#     | msend +--+              |  TCPdump    |                  | mreceive   |
#     +-------+                 |             |                  +------------+
#      10.0.1.11                +-------------+                    10.0.1.22
</pre>

**Comment by troglobit** [comment]
Looks good 👍 the second test needs to have the tcpdump port set as a multicast router port to see the IGMP/MLD traffic.
