### ISSUE TITLE
Add Bridge MDB support

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#334]
- MDB
  - [x] Add static mdb entry (MAC and IP)
  - [x] Del static mdb entry (MAC and IP)
- Operational
  - [x] List mdb
  - [ ] ~~List multicast router ports~~
  - [x] List multicast routers, per bridge or per VLAN
  - [x] List multicast status: on/off settings
  - [x] List per-port settings: flood, fast-leave, etc.
- Kernel
  - [ ] ~~Finalize kernel patch(es) and upstream~~
- Documentation
  - [x] Update `doc/networking.md`
  - [x] Mention filtering limitation (snooping must be on)
  - [x] Describe `mcast_flood` and how it is good for MAC multicast, e.g. industrial fieldbus protocols

> **Note:** due to how the MDB is implemented in the Linux bridge it is not possible to add MDB entries when multicast snooping is off.  This needs to be documented clearly.

### Tasks
 - Verify adding ports to a bridge enables snooping on ports
 - Verify toggling per-port multicast options take at runtime
 - ...

**Comment by troglobit** [comment]
Remaining task, for operational router ports, moved to #395.
