### ISSUE TITLE
Add DHCP relay agent, with Option 82 support

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#438]
## Description

In many network setups it can be convenient to implement easy-replacement of end devices using [DHCP Option 82](https://www.rfc-editor.org/rfc/rfc3046.html).  This is a feature where the DHCP request of a client is intercepted[^1] to attach another DHCP option which includes information about the switch itself and the port the client is connected to.  The relay agent then forwards the request to the DHCP server (one or many if redundancy is required), which in turn, based on policy, can either hand out a DHCP pool address or a fixed address reserved for the port on that switch.

Essentially, end devices would no longer just be devices with an IP address, but rather devices with _dedicated roles_ in a train car, or on a factory floor.  Replacing a broken end device with a new one shall[^2] yield the same IP address.

See issue #446 for details.

[^1]: ... intercepted by a DHCP relay agent on the switch the client is connected to.
[^2]: ... this is a server requirement that is not usually supported by common DHCP servers (ISC or dnsmasq), but is essentially a setting to ["preempt"](https://docs.westermo.com/weos/weos-5/General/DHCP-Server.html) a previous lease (promise from the server to a specific client), and hand it out to someone else claiming to be of the same identity (option 61 or 82).

## Tasks

- [ ] Investigate state of the [Westermo dhcp-helper](https://github.com/westermo/dhcp-helper) package
- [ ] Possibly fork and fix up `dhcp-helper` before packaging it for Infix
- [ ] YANG support for setting up Option 82 ("IP per port")
