### ISSUE TITLE
Upstream kernel patches

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#513]
### Tasks
- [ ] ~~core: Use NVMEM MAC address if available~~ (fixed upstream)
- [x] mvmdio: Speedups (v1,v2 sent; reviewed)
- [x] mvls: USXGMII fix (v1 sent)
- [x] mvls: Stats (v1,v2, v3, v4 sent; reviewed)
- [ ] mv10g: Firmware loading, power-up fixes, LED (v1 sent; stalled on DT bindings)
- [ ] mvls: LEDs (v1 sent; stalled: multiple people working on this upstream)

**Comment by troglobit** [comment]
CCB: Continuous work.
