### ISSUE TITLE
Full ietf-interfaces YANG support (advanced)

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#514]
### Tasks
- [x] [ietf-ip: ip:neighbor](https://github.com/kernelkit/infix/issues/819)
- [x] ietf-ip: ipv4+ipv6 mtu support
- [ ] ietf-intefaces: last-change
- [ ] ietf-intefaces: higher-layer-if
- [ ] ietf-intefaces: lower-layer-if
- [x] #152 
- [x] #515
