### ISSUE TITLE
Add support for MRP ring protocol

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#516]
### Tasks
 - [ ] #517
 - [ ] Update infix-if-bridge.yang model
 - [ ] Configurable NETCONF support for MRP
 - [ ] cli: add `show mrp` command, or similar
