### ISSUE TITLE
Add support for LLDP

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#518]
### Tasks
- [x] Add lldpd to system
- [ ] Should only run on e1, e2, e3, etc. not e1.10, lag0, br0, etc.
- [x] #119 
- [ ] Basic LLDP test
- [X] 053d9c213

**Comment by troglobit** [comment]
CCB: close, basic LLDP support now available since at least v25.01
