### ISSUE TITLE
Advanced bridge (snooping, stp)

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#519]
A basic bridge w/ multicast-snooping is defined in #83.  It needs to be extended with a few advanced features to cover the minimal scope for our customers.

### Tasks
- [x] Configurable IGMP/MLD querier support (#309)
- [x] bridge stp|rstp, with mstpd
- [x] #520
- [ ] Control BUM flooding to CPU
- [ ] MRP multicast quick-reconnect
