### ISSUE TITLE
ieee802-eth-if: statistics for ethernet-interface-half-duplex.yang

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#525]
### Tasks
- [ ] Add support for ethernet-interface-half-duplex.yang for counters which map in driver. 802.3 and yang
- [ ] Add deviations in infix-interface-half-duplex for unsupported counters
- [ ] Doc Yang to Ethtool mapping for the half-duplex counters
- [ ] Regression test for ethernet-interface-half-duplex.yang

[ethtool-to-yang.xlsx](https://github.com/user-attachments/files/16066888/ethtool-to-yang.xlsx)
