### ISSUE TITLE
Add test mode support with safe-config

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#561]
<img src="https://github.com/user-attachments/assets/446d0f6b-36a9-47e7-abb3-cd9e96e8858a" align="right">

### Overview

To facilitate testing of custom specific images, from customer specific trees, we need to add a "test mode" to the system.  Essentially, when the system boots it should look for, e.g., `/mnt/aux/test-mode` to trigger loading of a `safe-config` instead of the regular `startup-config`.

For some tests, however, we have to be able to reboot a DUT to verify a startup behavior.  To this end we need an *override* flag to be trigger a one-shot loading of the `startup-config`.

This test mode should be implemented as a separate `sysrepo-plugind` plugin, loaded by the system when it finds `/mnt/aux/test-mode`

### Tasks

 - [x] Sysrepo plugin to load when in *test mode*
   - New RPC: /test-reset, to restore a running system to `safe-config` before a new test
   - New RPC: /test-override, to enable *test override mode*, i.e., load startup-config
 - [ ] Modify `src/confd/bin/load` to select `/etc/safe-config.cfg` instead of `/cfg/startup-config.cfg` when in *test mode*
 - [ ] Modify `src/confd/bin/bootstrap` to generate `/etc/safe-config.cfg` when in *test mode*, just like `factory-config` and `failure-config` are generated today
 - [ ] Provision Qemu qcow image for qeneth with a default `/mnt/aux/test-mode` file
 - [ ] Document in `doc/testing.md`: describe the process of setting up a new DUT in a physical test system, may be to run a specific test that verifies topology connections and finishes off by creating `/mnt/aux/test-mode`

### Definition of `safe-config`

 - All system interfaces, except `lo` (loopback), in standalone mode, like in Infix' default `failure-config` does today
 - A dedicated default `hostname` for *test mode*, e.g., `test-mode`
 - NETCONF enabled, default SSH keys can be reused by specifying `genkey` as name, see `factory-config` generation
 - RESTCONF enabled, meaning the web server base must be enabled as well.

Other features can be left disbled, like netbrowse.
