### ISSUE TITLE
Add support for minimal defconfigs

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#597]
In an effort to streamline what are the *core Infix* requirements, as well speed up builds both in CI and on developer machines, we have arrived at a need for `$ARCH_minimal_defconfig` files.

### Tasks

 - [x] Replace the default builds in CI with minimal defconfigs
 - [x] Allow checkbox or ~~a CI keyword, similar to [[skip ci]](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs)~~ ... or pull request labels(!), to trigger default defconfigs
 - [x] Adapt Infamy to cope with restrictions of minimal builds, e.g., no containers or RESTCONF
 - [x] If default defconfigs are also selected for a job, use those images for Infamy
 - [x] Include Buildroot `.config` in image, similar to `/boot/config.gz`, to know exactly what is running
 - [x] Modify `/etc/os-release` for minimal builds
 - [x] How to identify, different hostname (`ix`) and bootup msg?

### Definition of minimal defconfig

 - No container support => no need to build Go compiler for podman
 - Smallest possible *CONF => NETCONF today
 - No extra/future packages, not even Tetris

> *How low can you go?*

**Comment by troglobit** [comment]
Turns out the best (?) or most intuitive way to control the flow for pull requests is to set a label when creating the PR, or afterwards (but before the next push to the branch).  

I've created the `ci:main` label to force branch builds to use the standard defconfigs.  This can also be triggered when starting jobs manually (workflow dispatch) from the Actions menu.  A dedicated checkbutton 'minimal' has been added, checked true by default.
