### ISSUE TITLE
Advanced Container Support

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#775]
### Tasks

- [ ] Inherit DNS from host (dnsmasq) instead of podman default
- [ ] Manage registries in configuration, including custom HTTPS certs
- [ ] Manage volumes in configuration (only basic named volumes)
- [ ] Support images from external media (encrypted?)
- [ ] Support shared mounts/volumes from external media

### Inherit DNS

It should be possible to inherit DNS from the host since we use dnsmasq and openresolv to handle static/dynamic (conf/dhc) DNS servers.  We could even leverage dnsmasq's `/etc/host` support by adding entries for all running containers, e.g. `CONTAINER-NAME.INFIX-HOST.DOMAIN`.

### Registries

- Local registries may require validation of self-signed https certs.
- Registries may take authentication, we need secure storage of auth. parameters somehow.
